name: ml_api
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - blas=1.0
  - ca-certificates=2021.5.25
  - certifi=2021.5.30
  - cycler=0.10.0
  - intel-openmp=2021.2.0
  - joblib=1.0.1
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - libxgboost=1.3.3
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - ncurses=6.2
  - numpy=1.20.2
  - numpy-base=1.20.2
  - olefile=0.46
  - openssl=1.1.1k
  - pandas=1.2.4
  - pip=21.1.2
  - plotly=4.14.3
  - py-xgboost=1.3.3
  - python=3.7.10
  - python-dateutil=2.8.1
  - pytz=2021.1
  - readline=8.1
  - retrying=1.3.3
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - setuptools=52.0.0
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.35.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - wheel=0.36.2
  - xgboost=1.3.3
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - ansi2html==1.6.0
    - argon2-cffi==20.1.0
    - argopt==0.7.0
    - async-generator==1.10
    - attrs==21.2.0
    - backcall==0.2.0
    - bleach==3.3.0
    - brotli==1.0.9
    - catboost==0.26
    - cffi==1.14.5
    - chardet==4.0.0
    - chart-studio==1.1.0
    - click==8.0.1
    - cloudpickle==1.6.0
    - colour==0.1.5
    - dash==1.20.0
    - dash-auth==1.4.1
    - dash-bootstrap-components==0.12.2
    - dash-core-components==1.16.0
    - dash-html-components==1.1.3
    - dash-renderer==1.9.1
    - dash-table==4.11.3
    - decorator==4.4.2
    - defusedxml==0.7.1
    - dill==0.3.4
    - dtreeviz==1.3
    - entrypoints==0.3
    - flask==2.0.1
    - flask-compress==1.10.1
    - flask-seasurf==0.3.0
    - flask-simplelogin==0.0.7
    - flask-wtf==0.15.1
    - future==0.18.2
    - idna==2.10
    - imageio==2.9.0
    - importlib-metadata==4.5.0
    - iniconfig==1.1.1
    - ipykernel==5.5.5
    - ipython==7.24.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - itsdangerous==2.0.1
    - jedi==0.18.0
    - jinja2==3.0.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.12
    - jupyter-console==6.4.0
    - jupyter-core==4.7.1
    - jupyter-dash==0.4.0
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - kiwisolver==1.3.1
    - lightgbm==3.2.1
    - lime==0.2.0.1
    - llvmlite==0.36.0
    - markupsafe==2.0.1
    - matplotlib==3.4.2
    - matplotlib-inline==0.1.2
    - mglearn==0.1.9
    - mistune==0.8.4
    - nbclient==0.5.3
    - nbconvert==6.1.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - networkx==2.5.1
    - nltk==3.6.2
    - notebook==6.4.0
    - numba==0.53.1
    - oyaml==1.0
    - packaging==20.9
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.2.0
    - pip-chill==1.0.1
    - pluggy==0.13.1
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.19
    - ptyprocess==0.7.0
    - py==1.10.0
    - pycparser==2.20
    - pygments==2.9.0
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - pytest==6.2.4
    - python-graphviz==0.16
    - pywavelets==1.1.1
    - pyyaml==5.4.1
    - pyzmq==22.1.0
    - qtconsole==5.1.0
    - qtpy==1.9.0
    - regex==2021.4.4
    - requests==2.25.1
    - scikit-image==0.18.1
    - seaborn==0.11.1
    - send2trash==1.7.1
    - shap==0.39.0
    - shortuuid==1.0.1
    - slicer==0.0.7
    - terminado==0.10.1
    - testpath==0.5.0
    - tifffile==2021.6.14
    - toml==0.10.2
    - tornado==6.1
    - tqdm==4.61.1
    - traitlets==5.0.5
    - typing-extensions==3.10.0.0
    - ua-parser==0.10.0
    - urllib3==1.26.6
    - waitress==2.0.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.0.1
    - widgetsnbextension==3.5.1
    - wtforms==2.3.3
    - zipp==3.4.1
